{% set version = "1.1.0" %}

package:
  name: pshell
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pshell/pshell-{{ version }}.tar.gz
  sha256: 01475c6e3220c1d66eabb25a03c315d79281cb410162dfb3e5d225897180f3bf

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - psutil >=3.2

test:
  imports:
    - pshell
  requires:
    - pytest >=3.1

about:
  home: https://github.com/crusaderky/pshell
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python API to completely replace bash scripting'

extra:
  recipe-maintainers:
    - crusaderky
