{% set version = "1.3.0" %}

package:
  name: pshell
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pshell/pshell-{{ version }}.tar.gz
  sha256: 1a63f22b4a0ab939cfd14b3144b8de40526483b016952d7739a6de643f3490cd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - psutil >=5.4

test:
  imports:
    - pshell
  requires:
    - pytest

about:
  home: https://github.com/crusaderky/pshell
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python API to completely replace bash scripting

extra:
  recipe-maintainers:
    - crusaderky
