{% set version = "1.4.0" %}

package:
  name: pshell
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pshell/pshell-{{ version }}.tar.gz
  sha256: 2965a01f0f056a481b61a684025191b2db06f751caa3517e642151eaf875a413

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=66
    - setuptools_scm
  run:
    - python >=3.8
    - psutil >=5.6

test:
  imports:
    - pshell
  requires:
    - pytest

about:
  home: https://github.com/crusaderky/pshell
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python API to completely replace bash scripting

extra:
  recipe-maintainers:
    - crusaderky
