travis:
  secure:
    BINSTAR_TOKEN: hCmWD5GlEEOr1x2W33AXf1YqIVXlkheZRWvnBimLKhjmzT3vR4jTnNk1pPhGPln5GA25PffCS/rCu4HH9AmTrIBhbjpQ2QV5u8c5A9r0PK7YpveiuWAmaeH1QJx75cOzYksTd+3HuVcPv3W32fIBQNmpR+i0vHmJFwdpznRYb4yrFwzLAnTEZVHkvQ+rovH4jiv5xef1JNYGrN3KOGW73s21FDJpCw3hhmDGI6qM4lg2j3RDIwS+nmoF3ESNHK6lQCcLp8Ai39C/6bStmA9Ouox/FHvWXHwawHfIRZjcTttuolM2wVSEEZxFe7pw344VnxqNOeewy2AdEF8kXzm6x7w0Dun4Sru70GfnYxMWMQCXLFB5zw3gBpY/f6JC+ZEGb5h85s1bDxu05sM7wBKjNxL+QmRGvMrj1agFJshs5YKpZkVaJPjA1IPo0JEvBcj+WNpCLc2+gfNihYsOUHJY0Hh/f6pYcjFUGVbUIYxMBG1Zlz+1lBl/m/zFMu35/yM7JeAG+aMg/3KaRAKyJXM1et/GRGnNPb8Bv/972ccX1Lvkj4Or7e9jOFh7+Yyg/SkiinWG8Kb3tw3WBcpjvLaQ/mRgaXwmBgIHiDI/Uv93WJ0g4l2f1/zcJgHlw93u9DuOX+QE00o8D+NzmMnD4xm9hwo9G3iR8Gnjw2MGTNOBbE0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
